spring:
  sql:
    init:
      mode: embedded
  jpa:
    defer-datasource-initialization: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL

sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8082